# Generated by Django 5.0.6 on 2025-06-29 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Título del Curso')),
                ('descripcion', models.TextField(verbose_name='Descripción Detallada')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio (USD)')),
                ('duracion_horas', models.IntegerField(verbose_name='Duración (horas)')),
                ('disponible', models.BooleanField(default=True, verbose_name='¿Disponible para Inscripción?')),
                ('nivel', models.CharField(choices=[('Basico', 'Básico'), ('Intermedio', 'Intermedio'), ('Avanzado', 'Avanzado')], default='Basico', max_length=20, verbose_name='Nivel de Dificultad')),
                ('idioma', models.CharField(default='Español', max_length=50, verbose_name='Idioma del Curso')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='cursos_imagenes/', verbose_name='Miniatura del Curso')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'ordering': ['fecha_creacion'],
            },
        ),
    ]
